# Generated by Django 3.1.2 on 2020-11-02 18:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0002_auto_20201102_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=tinymce.models.HTMLField(default=None),
        ),
    ]
