# Generated by Django 3.1.2 on 2020-11-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0003_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_thumbnail',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
