# Generated by Django 3.1.2 on 2020-11-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0004_category_cat_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
