# Generated by Django 3.1.2 on 2020-11-03 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0005_auto_20201103_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_thumbnail',
        ),
    ]
