# Generated by Django 3.1.2 on 2020-11-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0006_remove_category_cat_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_thumbnail',
            field=models.ImageField(default=2, upload_to='media'),
            preserve_default=False,
        ),
    ]
